name: build

on:
    push:
        branches:
            - master
    pull_request: ~

jobs:
    tests:
        runs-on: ubuntu-24.04
        strategy:
            matrix:
                php:
                    - '8.1'
                    - '8.2'
                    - '8.3'
                    - '8.4'
                    - '8.5'
                symfony: ['*']
                include:
                    - description: 'Symfony 6.4'
                      php: '8.1'
                      dependencies: lowest
                      symfony: 6.4.*
                    - description: 'Symfony 7.4'
                      php: '8.4'
                      symfony: 7.4.*
                    - description: 'Symfony 8.0'
                      php: '8.5'
                      symfony: 8.0.*
        name: PHP ${{ matrix.php }} tests (${{ matrix.description }})
        steps:
            - name: Checkout
              uses: actions/checkout@v6
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  tools: flex
              env:
                  COMPOSER_ALLOW_PLUGINS: symfony/flex
            - run: |
                  composer global require --no-interaction --no-progress symfony/flex:^2.10
                  composer config extra.symfony.require ${{ matrix.symfony }}
              if: matrix.symfony != '*'
            - name: Allow dev dependencies
              run: |
                  composer config minimum-stability dev
                  composer config prefer-stable true
              if: contains(matrix.symfony, '@dev')
            - name: Install dependencies
              uses: ramsey/composer-install@v3
              with:
                  dependency-versions: ${{ matrix.dependencies }}
              env:
                  SYMFONY_REQUIRE: ${{ matrix.symfony }}
            - name: Run tests
              run: vendor/bin/phpunit --colors=always

